<?php

declare(strict_types=1);

return [
    ['value' => 1, 'label' => 'London'],
    ['value' => 2, 'label' => 'New York'],
    ['value' => 3, 'label' => 'Paris'],
    ['value' => 4, 'label' => 'Tokyo'],
    ['value' => 5, 'label' => 'Los Angeles'],
    ['value' => 6, 'label' => 'Berlin'],
    ['value' => 7, 'label' => 'Sydney'],
    ['value' => 8, 'label' => 'Moscow'],
    ['value' => 9, 'label' => 'Toronto'],
    ['value' => 10, 'label' => 'Chicago'],
    ['value' => 11, 'label' => 'Madrid'],
    ['value' => 12, 'label' => 'Rome'],
    ['value' => 13, 'label' => 'Barcelona'],
    ['value' => 14, 'label' => 'San Francisco'],
    ['value' => 15, 'label' => 'Singapore'],
    ['value' => 16, 'label' => 'Seoul'],
    ['value' => 17, 'label' => 'Hong Kong'],
    ['value' => 18, 'label' => 'Dubai'],
    ['value' => 19, 'label' => 'Shanghai'],
    ['value' => 20, 'label' => 'Mumbai'],
    ['value' => 21, 'label' => 'Bangkok'],
    ['value' => 22, 'label' => 'Istanbul'],
    ['value' => 23, 'label' => 'Amsterdam'],
    ['value' => 24, 'label' => 'Vienna'],
    ['value' => 25, 'label' => 'Voronezh'],
    ['value' => 26, 'label' => 'Osaka'],
    ['value' => 27, 'label' => 'Beijing'],
    ['value' => 28, 'label' => 'Kuala Lumpur'],
    ['value' => 29, 'label' => 'Stockholm'],
    ['value' => 30, 'label' => 'Warsaw'],
    ['value' => 31, 'label' => 'Budapest'],
    ['value' => 32, 'label' => 'Prague'],
    ['value' => 33, 'label' => 'Dublin'],
    ['value' => 34, 'label' => 'Zurich'],
    ['value' => 35, 'label' => 'Brussels'],
    ['value' => 36, 'label' => 'Athens'],
    ['value' => 37, 'label' => 'Lisbon'],
    ['value' => 38, 'label' => 'Helsinki'],
    ['value' => 39, 'label' => 'Copenhagen'],
    ['value' => 40, 'label' => 'Edinburgh'],
    ['value' => 41, 'label' => 'Venice'],
    ['value' => 42, 'label' => 'Florence'],
    ['value' => 43, 'label' => 'Buenos Aires'],
    ['value' => 44, 'label' => 'Rio de Janeiro'],
    ['value' => 45, 'label' => 'Mexico City'],
    ['value' => 46, 'label' => 'São Paulo'],
    ['value' => 47, 'label' => 'Lima'],
    ['value' => 48, 'label' => 'Bogotá'],
    ['value' => 49, 'label' => 'Cairo'],
    ['value' => 50, 'label' => 'Jakarta']
];
