<?php

declare(strict_types=1);

return [
    ['value' => 1, 'label' => '1. London'],
    ['value' => 2, 'label' => '2. New York'],
    ['value' => 3, 'label' => '3. Paris'],
    ['value' => 4, 'label' => '4. Tokyo'],
    ['value' => 5, 'label' => '5. Los Angeles'],
    ['value' => 6, 'label' => '6. Berlin'],
    ['value' => 7, 'label' => '7. Sydney'],
    ['value' => 8, 'label' => '8. Moscow'],
    ['value' => 9, 'label' => '9. Toronto'],
    ['value' => 10, 'label' => '10. Chicago'],
    ['value' => 11, 'label' => '11. Madrid'],
    ['value' => 12, 'label' => '12. Rome'],
    ['value' => 13, 'label' => '13. Barcelona'],
    ['value' => 14, 'label' => '14. San Francisco'],
    ['value' => 15, 'label' => '15. Singapore'],
    ['value' => 16, 'label' => '16. Seoul'],
    ['value' => 17, 'label' => '17. Hong Kong'],
    ['value' => 18, 'label' => '18. Dubai'],
    ['value' => 19, 'label' => '19. Shanghai'],
    ['value' => 20, 'label' => '20. Mumbai'],
    ['value' => 21, 'label' => '21. Bangkok'],
    ['value' => 22, 'label' => '22. Istanbul'],
    ['value' => 23, 'label' => '23. Amsterdam'],
    ['value' => 24, 'label' => '24. Vienna'],
    ['value' => 25, 'label' => '25. Voronezh'],
    ['value' => 26, 'label' => '26. Osaka'],
    ['value' => 27, 'label' => '27. Beijing'],
    ['value' => 28, 'label' => '28. Kuala Lumpur'],
    ['value' => 29, 'label' => '29. Stockholm'],
    ['value' => 30, 'label' => '30. Warsaw'],
    ['value' => 31, 'label' => '31. Budapest'],
    ['value' => 32, 'label' => '32. Prague'],
    ['value' => 33, 'label' => '33. Dublin'],
    ['value' => 34, 'label' => '34. Zurich'],
    ['value' => 35, 'label' => '35. Brussels'],
    ['value' => 36, 'label' => '36. Athens'],
    ['value' => 37, 'label' => '37. Lisbon'],
    ['value' => 38, 'label' => '38. Helsinki'],
    ['value' => 39, 'label' => '39. Copenhagen'],
    ['value' => 40, 'label' => '40. Edinburgh'],
    ['value' => 41, 'label' => '41. Venice'],
    ['value' => 42, 'label' => '42. Florence'],
    ['value' => 43, 'label' => '43. Buenos Aires'],
    ['value' => 44, 'label' => '44. Rio de Janeiro'],
    ['value' => 45, 'label' => '45. Mexico City'],
    ['value' => 46, 'label' => '46. São Paulo'],
    ['value' => 47, 'label' => '47. Lima'],
    ['value' => 48, 'label' => '48. Bogotá'],
    ['value' => 49, 'label' => '49. Cairo'],
    ['value' => 50, 'label' => '50. Jakarta']
];
